import 'dart:io';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import '../../models/video_model.dart';
import '../../services/bunny_cdn_service.dart';
import '../../services/firestore_service.dart';

class AddVideoScreen extends StatefulWidget {
  final String courseId;

  const AddVideoScreen({super.key, required this.courseId});

  @override
  State<AddVideoScreen> createState() => _AddVideoScreenState();
}

class _AddVideoScreenState extends State<AddVideoScreen> {
  final _formKey = GlobalKey<FormState>();
  final _bunnyService = BunnyCDNService();
  final _firestoreService = FirestoreService();

  final _titleController = TextEditingController();
  final _descController = TextEditingController();
  final _durationController = TextEditingController(); // In minutes, ideally parsed from video
  final _orderController = TextEditingController(text: '1');

  File? _thumbnailFile;
  File? _videoFile;
  bool _isFree = false;
  bool _isLoading = false;
  double _uploadProgress = 0.0;
  String _uploadStatus = '';

  @override
  void dispose() {
    _titleController.dispose();
    _descController.dispose();
    _durationController.dispose();
    _orderController.dispose();
    super.dispose();
  }

  Future<void> _pickThumbnail() async {
    final picker = ImagePicker();
    final picked = await picker.pickImage(source: ImageSource.gallery);
    if (picked != null) {
      setState(() => _thumbnailFile = File(picked.path));
    }
  }

  Future<void> _pickVideo() async {
    FilePickerResult? result = await FilePicker.platform.pickFiles(
      type: FileType.video,
    );

    if (result != null) {
      setState(() => _videoFile = File(result.files.single.path!));
    }
  }

  Future<void> _uploadAndSave() async {
    if (!_formKey.currentState!.validate()) return;
    if (_videoFile == null) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Please select a video file')));
      return;
    }

    setState(() {
      _isLoading = true;
      _uploadStatus = 'Starting upload...';
    });

    try {
      // 1. Generate ID for video doc to use in paths
      // Actually we'll let Firestore gen ID, but for upload path we can use timestamp or random
      final tempVideoId = DateTime.now().millisecondsSinceEpoch.toString();

      // 2. Upload Thumbnail (if selected)
      String thumbnailUrl = '';
      if (_thumbnailFile != null) {
        setState(() => _uploadStatus = 'Uploading thumbnail...');
        thumbnailUrl = await _bunnyService.uploadImage(
          filePath: _thumbnailFile!.path,
          folder: 'video_thumbs',
        );
      }

      // 3. Upload Video
      setState(() => _uploadStatus = 'Uploading video (this may take time)...');
      String videoUrl = await _bunnyService.uploadVideo(
        filePath: _videoFile!.path,
        courseId: widget.courseId,
        videoId: tempVideoId,
        onProgress: (sent, total) {
          setState(() {
            _uploadProgress = sent / total;
          });
        },
      );

      // 4. Save to Firestore
      final video = VideoModel(
        id: '', // Generated by Firestore
        courseId: widget.courseId,
        title: _titleController.text.trim(),
        description: _descController.text.trim(),
        videoUrl: videoUrl,
        thumbnailUrl: thumbnailUrl,
        duration: _durationController.text.trim().isEmpty ? '5:00' : '${_durationController.text.trim()}:00',
        orderIndex: int.tryParse(_orderController.text) ?? 0,
        isFree: _isFree,
        isPublished: true,
        createdAt: DateTime.now(),
      );

      await _firestoreService.addVideo(video);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Video uploaded successfully!')));
        Navigator.pop(context);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: $e')));
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Add Video')),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Video File Picker
              GestureDetector(
                onTap: _pickVideo,
                child: Container(
                  height: 150,
                  width: double.infinity,
                  decoration: BoxDecoration(
                    color: Colors.black12,
                    borderRadius: BorderRadius.circular(12),
                    border: Border.all(color: Colors.grey),
                  ),
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      Icon(Icons.video_file, size: 50, color: _videoFile != null ? Colors.green : Colors.grey),
                      const SizedBox(height: 8),
                      Text(
                        _videoFile != null ? _videoFile!.path.split('/').last : 'Tap to select Video',
                        textAlign: TextAlign.center,
                        style: const TextStyle(fontWeight: FontWeight.bold),
                      ),
                    ],
                  ),
                ),
              ),
              const SizedBox(height: 16),

              // Thumbnail Picker
              GestureDetector(
                onTap: _pickThumbnail,
                child: Row(
                  children: [
                    Container(
                      height: 80,
                      width: 120,
                      decoration: BoxDecoration(
                        color: Colors.grey[200],
                        borderRadius: BorderRadius.circular(8),
                        image: _thumbnailFile != null
                            ? DecorationImage(
                                image: FileImage(_thumbnailFile!),
                                fit: BoxFit.cover,
                              )
                            : null,
                      ),
                      child: _thumbnailFile == null ? const Icon(Icons.image) : null,
                    ),
                    const SizedBox(width: 16),
                    const Text('Select Thumbnail (Optional)'),
                  ],
                ),
              ),
              const SizedBox(height: 16),

              // Fields
              TextFormField(
                controller: _titleController,
                decoration: const InputDecoration(labelText: 'Video Title', border: OutlineInputBorder()),
                validator: (v) => v!.isEmpty ? 'Required' : null,
              ),
              const SizedBox(height: 16),
              
              Row(
                children: [
                  Expanded(
                    child: TextFormField(
                      controller: _durationController,
                      decoration: const InputDecoration(labelText: 'Duration (mins)', border: OutlineInputBorder()),
                      keyboardType: TextInputType.number,
                      validator: (v) => v!.isEmpty ? 'Required' : null,
                    ),
                  ),
                  const SizedBox(width: 16),
                  Expanded(
                    child: TextFormField(
                      controller: _orderController,
                      decoration: const InputDecoration(labelText: 'Order Index', border: OutlineInputBorder()),
                      keyboardType: TextInputType.number,
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 16),
              
              SwitchListTile(
                title: const Text('Is this a Free Preview?'),
                value: _isFree,
                onChanged: (v) => setState(() => _isFree = v),
              ),
              const SizedBox(height: 16),

              TextFormField(
                controller: _descController,
                decoration: const InputDecoration(labelText: 'Description', border: OutlineInputBorder()),
                maxLines: 3,
              ),

              const SizedBox(height: 24),

              // Progress Bar
              if (_isLoading) ...[
                Text(_uploadStatus),
                const SizedBox(height: 8),
                LinearProgressIndicator(value: _uploadProgress),
                const SizedBox(height: 24),
              ],

              // Submit
              SizedBox(
                width: double.infinity,
                height: 50,
                child: ElevatedButton(
                  onPressed: _isLoading ? null : _uploadAndSave,
                  child: const Text('Upload Video'),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
